### ISSUE TITLE
Add model `search_fields`

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#361]
After a recent Wagtail update, there are several warnings:

```
WARNINGS:
community.CommunityDirectory: (wagtailsearch.W001) Core Page fields missing in `search_fields`
        HINT: Ensure that CommunityDirectory extends the Page model search fields `search_fields = Page.search_fields + [...]`
community.OnlineWorship: (wagtailsearch.W001) Core Page fields missing in `search_fields`
        HINT: Ensure that OnlineWorship extends the Page model search fields `search_fields = Page.search_fields + [...]`
contact.Meeting: (wagtailsearch.W001) Core Page fields missing in `search_fields`
        HINT: Ensure that Meeting extends the Page model search fields `search_fields = Page.search_fields + [...]`
contact.Organization: (wagtailsearch.W001) Core Page fields missing in `search_fields`
        HINT: Ensure that Organization extends the Page model search fields `search_fields = Page.search_fields + [...]`
contact.Person: (wagtailsearch.W001) Core Page fields missing in `search_fields`
        HINT: Ensure that Person extends the Page model search fields `search_fields = Page.search_fields + [...]`
events.Event: (wagtailsearch.W001) Core Page fields missing in `search_fields`
        HINT: Ensure that Event extends the Page model search fields `search_fields = Page.search_fields + [...]`
```

## Task

- [ ] add `search_fields` to all models that are causing warnings
