### ISSUE TITLE
Use CSS instead of JavaScript for responsive embed video iframes

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#733]
We currently use the Fitvids JavaScript library to ensure embedded videos render well on all devices. By default, the videos are rendered with 250px width, making them difficult to view on larger screens.

There may be a CSS-only solution for responsive video embeds taken from the Wagtail Bakery:

```css
/* stylelint-disable-next-line selector-class-pattern */
.block-paragraph_block iframe {
  aspect-ratio: 16 / 9;
  width: 100%;
  height: 100%;
}
```
https://github.com/wagtail/bakerydemo/pull/418/files

To target the embedded videos, let's try the CSS-only approach with a more specific CSS selector than `.block-paragraph_block iframe`.

**Comment by brylie** [comment]
@ErnstBas, would you like to take this task?

**Comment by ErnstBas** [comment]
If you're not in a hurry, I would like to give it a go. I've got a bit of a busy week ahead, so I won't have much time in the next few days. I have a basic understanding of CSS, so it'll be nice to delve into this and discover something new.

**Comment by brylie** [comment]
Sure, this task isn't urgent or critical.

**Comment by ErnstBas** [comment]
Hello @brylie, It seems already to work with a simple fix adding the following code to `wf_website.css`:

```css
iframe {
  aspect-ratio: 16 / 9;
  width: 100%;
  height: 100%;
}
```

This solution could, of course, affect other inline frames that may not contain videos. You mentioned that you wanted a more specific CSS selector. I'm having a bit of trouble finding the part in the code where we can add such a selector.
